/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edoo_s8_teoria_Ejercicios;

import javax.swing.JOptionPane;

/**
 *
 * @author LUCANO
 */
public class FrmEjercicios extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjercicio01
     */
    public FrmEjercicios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtExpr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        txtPalabra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnVerificar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtB10 = new javax.swing.JTextField();
        cbxBase = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtExpr.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Expresion"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ejercicios - Teoría");

        btnVerificar.setText("Verificar Si los paréntesis están correctamente balanceados");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        txtPalabra.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Palabra"));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnVerificar1.setText("Verificar Si la palabra es palíndrome");
        btnVerificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificar1ActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txtB10.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar número en Base 10"));

        cbxBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base...", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        cbxBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Convertir a base:"));

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtB10, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(37, 37, 37)
                                                    .addComponent(cbxBase, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnVerificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtExpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtB10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxBase, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        boolean valor = verificarParentesis(txtExpr.getText());
        if(valor)
            JOptionPane.showMessageDialog(null, "La expresión contiene paréntesis correctamente balanceados.");
        else
            JOptionPane.showMessageDialog(null, "La expresión NO contiene paréntesis correctamente balanceados.");
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnVerificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificar1ActionPerformed
        boolean valor = verificarPalindrome(txtPalabra.getText());
        if(valor)
            JOptionPane.showMessageDialog(null, "La palabra es palíndrome.");
        else
            JOptionPane.showMessageDialog(null, "La palabra NO es palíndrome.");
    }//GEN-LAST:event_btnVerificar1ActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        convertirABase(Integer.parseInt(txtB10.getText()), Integer.parseInt(String.valueOf(cbxBase.getSelectedIndex() + 1)));
    }//GEN-LAST:event_btnConvertirActionPerformed

    

    public boolean verificarParentesis(String expresion) {
        Pila<Character> p = new Pila<>();
        int n = expresion.length();

        for (int i = 0; i < n; i++) {
            char x = expresion.charAt(i);

            if (x == '(') {
                p.push(x);
            } 
            else if (x == ')') {
                if (p.isEmpty()) {
                    return false; 
                }
                p.pop(); 
            }
        }

        return p.isEmpty();
    }
    
    
    public boolean verificarPalindrome(String palabra){
        Pila<Character> p = new Pila<>();
        int n = palabra.length();
        char x;
        int num;
        
        for (int i = 0; i < n; i++) {
            x = palabra.charAt(i);
            p.push(x);
        }
        for (int i = 0; i < n; i++) {
            x = palabra.charAt(i);
            if(p.pop()!=x)
                return false;
        }
        return true;
    }
    
    
    public void convertirABase(int num, int base) {
        Pila<Character> p = new Pila<>();
        StringBuilder resultado = new StringBuilder();

        while (num != 0) {
            int residuo = num % base;
            if (residuo < 10) {
                p.push((char) (residuo + 48));
            } else {
                p.push((char) (residuo + 55));
            }
            num /= base;
        }

        while (!p.isEmpty()) {
            resultado.append(p.pop());
        }

        JOptionPane.showMessageDialog(null, "Número en base " + base + ": " + resultado.toString());
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVerificar1;
    private javax.swing.JComboBox<String> cbxBase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtB10;
    private javax.swing.JTextField txtExpr;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
