/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edoo_s8_teoria_Notaciones;

/**
 *
 * @author LUCANO
 */
public class FrmEjercicioNotaciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjercicioNotaciones
     */
    public FrmEjercicioNotaciones() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNotacionInfija = new javax.swing.JTextField();
        txtNotacionPostfija = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNotacionInfija.setBorder(javax.swing.BorderFactory.createTitledBorder("Notacion InFija"));

        txtNotacionPostfija.setBorder(javax.swing.BorderFactory.createTitledBorder("Notacion PostFija"));
        txtNotacionPostfija.setEnabled(false);

        txtResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        txtResultado.setEnabled(false);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotacionPostfija, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotacionInfija, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtNotacionInfija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtNotacionPostfija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String e_infija = txtNotacionInfija.getText();
        txtNotacionPostfija.setText(infija_PostFija(e_infija));
        txtResultado.setText(String.valueOf(calcular(txtNotacionPostfija.getText())));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNotacionInfija.setText("");
        txtNotacionPostfija.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public String infija_PostFija(String expresion){
        Pila<Character> p = new Pila();
        
        StringBuilder postfija = new StringBuilder();
        
        int n = expresion.length();
        char x;
        for (int i = 0; i < n; i++) {
            x = expresion.charAt(i);
            
            if(x == '(')
                p.push(x);
            if(x == ')'){
                while(!p.isEmpty() && p.top() != '(')
                    postfija.append(p.pop());
                p.pop();
            }
            if(x=='+' || x=='-' || x=='*' || x=='/')
                if(p.isEmpty() || ((x=='*' || x=='/') && (p.top() == '+' || p.top() == '-')) || p.top()=='(')
                    p.push(x);
                else{
                    while((!p.isEmpty())             &&               ((x=='+') || (x=='-') || (x=='*' && p.top()=='/') || (x=='/' && p.top()=='*')) )
                        postfija.append(p.pop());
                    p.push(x);
                }
            if(x>=48 && x<=57)
                postfija.append(x);
        }
        while (!p.isEmpty()) {
            postfija.append(p.pop());
        }
        return postfija.toString();
    }
    
    public double calcular(String expresion){
        Pila<Double> p = new Pila();
        
        int n = expresion.length();
        char x;
        
        for (int i = 0; i < n; i++) {
            x = expresion.charAt(i);
            if (x >= 48 && x <= 57) 
                p.push((double) Character.getNumericValue(x));
            if(x=='+' || x=='-' || x=='*' || x=='/'){
                double op2 = p.pop();
                double op1 = p.pop();
                if(x=='+')
                    p.push(op1+op2);
                if(x=='-')
                    p.push(op1-op2);
                if(x=='/')
                    p.push(op1/op2);
                if(x=='*')
                    p.push(op1*op2);
            }  
        }
        return p.pop();   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField txtNotacionInfija;
    private javax.swing.JTextField txtNotacionPostfija;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
